<?php
$admin_title='Gerenciar Usuários'; include __DIR__.'/includes/header.php';
$msg=''; $erro=''; $edit=isset($_GET['edit'])&&$pdo?db_one($pdo,'SELECT * FROM usuarios WHERE id=?',[(int)$_GET['edit']]):null;
if ($_SERVER['REQUEST_METHOD']==='POST' && $pdo) {
  $id=(int)($_POST['id']??0); $nome=trim($_POST['nome']??''); $email=strtolower(trim($_POST['email']??'')); $nivel=($_POST['nivel_acesso']??'user')==='admin'?'admin':'user'; $status=($_POST['status']??'ativo')==='inativo'?'inativo':'ativo'; $senha=$_POST['senha']??'';
  if (!verify_csrf($_POST['csrf_token']??null)) $erro='Token de segurança inválido.';
  elseif ($nome==='' || !filter_var($email,FILTER_VALIDATE_EMAIL)) $erro='Informe nome e e-mail válidos.';
  elseif (!$id && strlen($senha)<8) $erro='A senha deve ter pelo menos 8 caracteres.';
  elseif (db_one($pdo,'SELECT id FROM usuarios WHERE email=? AND id<>?',[$email,$id])) $erro='Este e-mail já está em uso.';
  else { if($id){$sql='UPDATE usuarios SET nome=?,email=?,nivel_acesso=?,status=?'.($senha!==''?',senha=?':'').' WHERE id=?';$params=[$nome,$email,$nivel,$status];if($senha!=='')$params[]=password_hash($senha,PASSWORD_DEFAULT);$params[]=$id;$pdo->prepare($sql)->execute($params);}else{$pdo->prepare('INSERT INTO usuarios(nome,email,senha,nivel_acesso,status) VALUES(?,?,?,?,?)')->execute([$nome,$email,password_hash($senha,PASSWORD_DEFAULT),$nivel,$status]);}$msg='Usuário salvo com sucesso.'; $edit=null; }
}
if(isset($_GET['delete'])&&$pdo&&verify_csrf($_GET['token']??null)){ $id=(int)$_GET['delete']; if($id!==(int)($_SESSION['admin_id']??0)){$pdo->prepare('DELETE FROM usuarios WHERE id=?')->execute([$id]);$msg='Usuário excluído.';} }
$users=$pdo?db_rows($pdo,'SELECT id,nome,email,nivel_acesso,status,criado_em FROM usuarios ORDER BY criado_em DESC'):[];
?><main class="admin-content"><div class="admin-heading"><div><h1>Gerenciar Usuários</h1><p class="muted">Controle acessos e contas cadastradas.</p></div><a class="btn btn-primary" href="?novo=1">+ Novo usuário</a></div><?php if($msg): ?><div class="notice success"><?= e($msg) ?></div><?php endif; ?><?php if($erro): ?><div class="notice error"><?= e($erro) ?></div><?php endif; ?><div class="admin-panel"><?php if($edit||isset($_GET['novo'])): ?><h2><?= $edit?'Editar usuário':'Novo usuário' ?></h2><form class="admin-form" method="post"><input type="hidden" name="id" value="<?= e((string)($edit['id']??0)) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><label>Nome<input name="nome" required value="<?= e($edit['nome']??'') ?>"></label><label>E-mail<input type="email" name="email" required value="<?= e($edit['email']??'') ?>"></label><label>Senha <?= $edit?'<small class="muted">Deixe em branco para manter a atual.</small>':'' ?><input type="password" name="senha" <?= $edit?'':'required minlength="8"' ?> autocomplete="new-password"></label><label>Nível de acesso<select name="nivel_acesso"><option value="user" <?= (($edit['nivel_acesso']??'user')==='user')?'selected':'' ?>>User</option><option value="admin" <?= (($edit['nivel_acesso']??'')==='admin')?'selected':'' ?>>Admin</option></select></label><label>Status<select name="status"><option value="ativo" <?= (($edit['status']??'ativo')==='ativo')?'selected':'' ?>>Ativo</option><option value="inativo" <?= (($edit['status']??'')==='inativo')?'selected':'' ?>>Inativo</option></select></label><div><button class="btn btn-primary">Salvar usuário</button> <a class="btn btn-outline" href="gerenciar_usuarios.php">Cancelar</a></div></form><?php else: ?><table class="admin-table"><thead><tr><th>Nome</th><th>E-mail</th><th>Nível</th><th>Status</th><th>Cadastro</th><th>Ações</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><strong><?= e($u['nome']) ?></strong></td><td><?= e($u['email']) ?></td><td><?= e(ucfirst($u['nivel_acesso'])) ?></td><td><span class="status status-<?= e($u['status']??'ativo') ?>"><?= e(ucfirst($u['status']??'ativo')) ?></span></td><td><?= e(date('d/m/Y',strtotime($u['criado_em']))) ?></td><td><a href="?edit=<?= (int)$u['id'] ?>">Editar</a> &nbsp; <a href="?delete=<?= (int)$u['id'] ?>&token=<?= e(csrf_token()) ?>" onclick="return confirm('Excluir este usuário?')">Excluir</a></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div></main><?php include __DIR__.'/includes/footer.php'; ?>
